import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  ScanLine,
  Upload,
  Camera,
  CheckCircle,
  AlertTriangle,
  ShieldAlert,
  Sparkles,
  FileDown,
  UserCheck,
  Leaf,
  Bug,
  HelpCircle,
} from 'lucide-react';
import { apiRequest } from '../../api/client';
import { DiseaseDetectionResult } from '../../types';

export const DiseaseDetectionPage: React.FC = () => {
  const [selectedImage, setSelectedImage] = useState<string>(
    'https://images.unsplash.com/photo-1592417817098-8f3d6eb19657?auto=format&fit=crop&w=800&q=80'
  );
  const [cropHint, setCropHint] = useState<string>('Tomato');
  const [isScanning, setIsScanning] = useState<boolean>(false);
  const [result, setResult] = useState<DiseaseDetectionResult | null>({
    cropName: 'Tomato',
    predictedDisease: 'Tomato Early Blight (Alternaria solani)',
    confidenceScore: 94.2,
    severity: 'MODERATE',
    symptoms: [
      'Concentric dark brown circular rings on lower leaves (target-board appearance)',
      'Yellow chlorotic halos surrounding leaf spots',
      'Premature defoliation starting from ground-level foliage',
    ],
    treatments: {
      chemical: [
        'Mancozeb 75% WP @ 2g per liter of water',
        'Copper Oxychloride 50% WP @ 2.5g per liter',
        'Azoxystrobin 23% SC @ 1 ml per liter',
      ],
      organic: [
        'Neem oil spray (10,000 ppm) @ 5 ml per liter with liquid soap spreader',
        'Trichoderma viride bio-fungicide soil drenching',
        'Baking soda solution (5g/L) + Panchagavya spray',
      ],
      dosageInfo: 'Spray evenly during morning or late afternoon. Repeat after 7-10 days if humid weather persists.',
    },
    prevention: [
      'Practice 2 to 3 year crop rotation with non-solanaceous crops (e.g. legumes or corn)',
      'Ensure wide spacing between plants for adequate airflow',
      'Avoid overhead sprinkler irrigation; use drip irrigation to keep foliage dry',
    ],
    disclaimer:
      'AI Diagnosis Notice: This prediction is generated by automated vision models. Always inspect field conditions and consult an authorized agricultural expert before applying chemical pesticides.',
    expertEscalationRecommended: false,
  });

  const sampleLeaves = [
    {
      label: 'Tomato Early Blight',
      hint: 'Tomato',
      url: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb19657?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Paddy Bacterial Blight',
      hint: 'Paddy',
      url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Wheat Stripe Rust',
      hint: 'Wheat',
      url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=800&q=80',
    },
    {
      label: 'Cotton Leaf Curl Virus',
      hint: 'Cotton',
      url: 'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=800&q=80',
    },
  ];

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const reader = new FileReader();
      reader.onload = () => {
        if (reader.result) {
          setSelectedImage(reader.result as string);
        }
      };
      reader.readAsDataURL(file);
    }
  };

  const handleScan = async () => {
    setIsScanning(true);
    const res = await apiRequest('/ai/disease-detection', {
      method: 'POST',
      body: JSON.stringify({ imageUrl: selectedImage, cropHint }),
    });

    setIsScanning(false);
    if (res.success && res.result) {
      setResult(res.result);
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in max-w-6xl mx-auto">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-200 dark:border-slate-800 pb-6">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-teal-100 dark:bg-teal-950 text-teal-800 dark:text-teal-300 text-xs font-bold mb-2">
            <ScanLine className="w-3.5 h-3.5" />
            <span>CNN Deep Learning Diagnostic Engine</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white">
            Crop Disease Detection (पौधों की बीमारी पहचान)
          </h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Upload or capture a leaf photograph to classify plant pathology and receive verified organic & chemical treatments.
          </p>
        </div>

        <button
          onClick={() => window.print()}
          className="flex items-center gap-2 px-4 py-2.5 rounded-2xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 text-sm font-bold shadow-sm hover:bg-slate-50 transition self-start"
        >
          <FileDown className="w-4 h-4" />
          <span>Download Disease Report</span>
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Col: Image Upload & Preview */}
        <div className="lg:col-span-5 space-y-6">
          <div className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 shadow-sm space-y-5">
            <h2 className="font-bold text-base text-slate-900 dark:text-white flex items-center gap-2">
              <Camera className="w-5 h-5 text-teal-600" />
              <span>Leaf Photograph Upload</span>
            </h2>

            {/* Image Preview Box */}
            <div className="relative aspect-video rounded-2xl overflow-hidden border-2 border-dashed border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 flex items-center justify-center group">
              <img
                src={selectedImage}
                alt="Selected Leaf"
                className="w-full h-full object-cover group-hover:scale-105 transition duration-300"
              />
              {isScanning && (
                <div className="absolute inset-0 bg-teal-950/70 backdrop-blur-sm flex flex-col items-center justify-center text-white space-y-3">
                  <div className="w-12 h-12 border-4 border-teal-400 border-t-transparent rounded-full animate-spin" />
                  <p className="text-sm font-bold animate-pulse">Running CNN Feature Extractor...</p>
                </div>
              )}
            </div>

            {/* Upload Buttons */}
            <div className="grid grid-cols-2 gap-3">
              <label className="cursor-pointer flex items-center justify-center gap-2 py-3 px-4 rounded-2xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-bold text-xs transition text-center">
                <Upload className="w-4 h-4" />
                <span>Upload Leaf File</span>
                <input
                  type="file"
                  accept="image/jpeg,image/png,image/webp"
                  onChange={handleFileUpload}
                  className="hidden"
                />
              </label>

              <button
                type="button"
                onClick={() => alert('Mobile Camera Active — Take clean photo of infected leaf surface.')}
                className="flex items-center justify-center gap-2 py-3 px-4 rounded-2xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-bold text-xs transition text-center"
              >
                <Camera className="w-4 h-4" />
                <span>Camera Capture</span>
              </button>
            </div>

            {/* Crop Hint */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 dark:text-slate-300 mb-1">
                Select Crop Type (optional hint)
              </label>
              <select
                value={cropHint}
                onChange={(e) => setCropHint(e.target.value)}
                className="w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 px-3 py-2 text-xs font-medium text-slate-900 dark:text-white"
              >
                <option value="Tomato">Tomato (टमाटर)</option>
                <option value="Paddy">Rice / Paddy (धान)</option>
                <option value="Wheat">Wheat (गेहूं)</option>
                <option value="Cotton">Cotton (कपास)</option>
                <option value="Potato">Potato (आलू)</option>
              </select>
            </div>

            {/* Scan Trigger Button */}
            <button
              onClick={handleScan}
              disabled={isScanning}
              className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-teal-600 to-emerald-600 hover:from-teal-700 hover:to-emerald-700 text-white font-bold text-sm shadow-md shadow-teal-600/30 transition flex items-center justify-center gap-2"
            >
              <Sparkles className="w-4 h-4" />
              <span>{isScanning ? 'Diagnosing Disease...' : 'Scan Leaf with AI'}</span>
            </button>
          </div>

          {/* Sample Benchmark Leaves */}
          <div className="p-4 rounded-3xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700 space-y-3">
            <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">
              Try Sample Infected Leaves
            </p>
            <div className="grid grid-cols-2 gap-2">
              {sampleLeaves.map((sample, i) => (
                <button
                  key={i}
                  onClick={() => {
                    setSelectedImage(sample.url);
                    setCropHint(sample.hint);
                  }}
                  className="p-2 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 hover:border-teal-500 text-left text-xs font-medium truncate text-slate-700 dark:text-slate-200 transition"
                >
                  🍃 {sample.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Right Col: Diagnosis & Treatment Results */}
        <div className="lg:col-span-7 space-y-6">
          {result && (
            <div className="rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 sm:p-8 shadow-sm space-y-6">
              {/* Diagnosis Header Card */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700">
                <div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                    Diagnostic Finding for {result.cropName}
                  </span>
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white mt-0.5">
                    {result.predictedDisease}
                  </h3>
                  <div className="flex items-center gap-2 mt-2">
                    <span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300">
                      Severity: {result.severity}
                    </span>
                    {result.confidenceScore < 75 && (
                      <span className="text-xs font-bold px-2.5 py-0.5 rounded-full bg-rose-100 text-rose-800 dark:bg-rose-950 dark:text-rose-300 flex items-center gap-1">
                        <AlertTriangle className="w-3.5 h-3.5" />
                        Low Confidence
                      </span>
                    )}
                  </div>
                </div>

                <div className="text-right sm:self-start">
                  <span className="text-3xl font-extrabold text-teal-600 dark:text-teal-400">
                    {result.confidenceScore}%
                  </span>
                  <p className="text-[10px] font-bold text-slate-400 uppercase">AI Confidence</p>
                </div>
              </div>

              {/* Symptoms */}
              <div>
                <h4 className="font-bold text-sm text-slate-900 dark:text-white flex items-center gap-2 mb-2">
                  <Bug className="w-4 h-4 text-amber-500" />
                  <span>Observed Plant Symptoms (लक्षण)</span>
                </h4>
                <ul className="space-y-1.5 text-xs text-slate-600 dark:text-slate-300 list-disc pl-5">
                  {result.symptoms.map((s, idx) => (
                    <li key={idx} className="leading-relaxed">{s}</li>
                  ))}
                </ul>
              </div>

              {/* Treatments: Organic vs Chemical */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Organic Treatment */}
                <div className="p-4 rounded-2xl bg-emerald-50/70 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800 text-xs space-y-2">
                  <p className="font-bold text-emerald-800 dark:text-emerald-300 flex items-center gap-1.5">
                    <Leaf className="w-4 h-4" />
                    <span>Organic & Bio-Remedies (जैविक उपचार)</span>
                  </p>
                  <ul className="space-y-1 text-emerald-950 dark:text-emerald-200">
                    {result.treatments.organic.map((t, idx) => (
                      <li key={idx}>• {t}</li>
                    ))}
                  </ul>
                </div>

                {/* Chemical Treatment */}
                <div className="p-4 rounded-2xl bg-blue-50/70 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-800 text-xs space-y-2">
                  <p className="font-bold text-blue-800 dark:text-blue-300 flex items-center gap-1.5">
                    <ShieldAlert className="w-4 h-4" />
                    <span>Approved Chemical Treatment</span>
                  </p>
                  <ul className="space-y-1 text-blue-950 dark:text-blue-200">
                    {result.treatments.chemical.map((t, idx) => (
                      <li key={idx}>• {t}</li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Dosage information */}
              <div className="p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 text-xs text-slate-700 dark:text-slate-300">
                <span className="font-bold text-slate-900 dark:text-white">Dosage & Spray Schedule: </span>
                {result.treatments.dosageInfo}
              </div>

              {/* FR-037 Disclaimer Notice */}
              <div className="p-3 rounded-xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 text-[11px] text-amber-900 dark:text-amber-200 flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 shrink-0 text-amber-600 mt-0.5" />
                <p className="leading-relaxed">{result.disclaimer}</p>
              </div>

              {/* FR-038 Escalate to Expert Button */}
              <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-2 border-t border-slate-100 dark:border-slate-800">
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Uncertain about diagnosis or need custom treatment?
                </p>
                <Link
                  to="/expert-consultation"
                  className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-agro-600 hover:bg-agro-500 text-white font-bold text-xs shadow transition shrink-0"
                >
                  <UserCheck className="w-4 h-4" />
                  <span>Consult Agricultural Specialist</span>
                </Link>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
